### PR TITLE
1 cannot publish due to jsr compatibility issues

### LINKED ISSUE #1: cannot publish due to JSR compatibility issues
hey @masonmark JSR says [get off the elephant tranquilizer](https://github.com/axhxrx/validated-string/actions/runs/12329984329/job/34414933026) you madman

i'll give it another go-round when i get back from the discotheque if you can fix those problemas

### PR DESCRIPTION
**Pull request by masonmark**
Does this satisfy the constraints? @protiev I don't think we can know until publishing is attempted again — merging this enough to do that?

### CODE REVIEW

**Comment by protiev** [comment]
yah

**Comment by masonmark** [comment]
haha haha you right, this is [lame](https://github.com/axhxrx/validated-string/actions/runs/12330449197/job/34415932011)

maybe there is way to dry-run? i'm in the pub^Wdiscotheque so i cant check atm

**Comment by protiev** [comment]
haha haha you right, this is [lame](https://github.com/axhxrx/validated-string/actions/runs/12330449197/job/34415932011)

maybe there is way to dry-run? i'm in the pub^Wdiscotheque so i cant check atm

**Comment by masonmark** [comment]
Well I think [there is a dry-run option](https://github.com/jsr-io/jsr/issues/444#issuecomment-2080191576) at least — although we might have to change how the lib is published? Not sure, that's your department. Maybe when you get back from the, uh, discotheque, you can see if the GHA action support `--dry-run` or whatever.

**Comment by protiev** [comment]
i think i prefer you just manually keep making PRs until works

but i see what i can do

**Pull request merged**
